name: "CI/CD"
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to server
      run: |
        echo $HOSTNAME
        hostname -I
        source $HOME/streamlit_venv/bin/activate
        cd $HOME/postamat/
        git pull
    - name: Install requirements
      run: |
        echo $HOSTNAME
        hostname -I
        source $HOME/streamlit_venv/bin/activate
        cd $HOME/postamat/
        pip install -q -r requirements.txt
    - name: Restart service
      run: |
        echo $HOSTNAME
        hostname -I
        systemctl restart postamat.service
        systemctl status postamat.service
