name: CI/CD
on:
  push:
    branches: [master]
  pullrequest:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      — uses: actions/checkout@v2
      — run: |
          echo $HOSTNAME
